# Generated by Django 2.2.5 on 2021-01-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
