# Generated by Django 2.2.5 on 2021-01-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumabeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('elapsed_time', models.IntegerField()),
                ('elapsed_days', models.IntegerField()),
            ],
        ),
    ]
