# Generated by Django 2.2.5 on 2021-01-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_consumabemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsumabeModel',
            new_name='ConsumableModel',
        ),
    ]
