# Generated by Django 2.2.5 on 2021-01-22 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210121_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumablemodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='consumablemodel',
            name='time',
        ),
        migrations.AddField(
            model_name='consumablemodel',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
